### PR TITLE
Fix logic - it was wrong way round

### PR DESCRIPTION
**Pull request by FreddieAkeroyd**
Test was leading to wrong branch being called

### CODE REVIEW

**Comment by Tom-Willemsen** [comment]
We should add a [unit|system] test that would have caught this bug.

**Comment by FreddieAkeroyd** [comment]
Test is via google test. To run tests type "make test" in top of webget module

**Comment by Tom-Willemsen** [comment]
I am getting the following error (along with a "failed to start" dialog box) when I try to run the tests:

```
c:\Instrument\Apps\EPICS\support\webget\master>make test
make: Entering directory 'c:/Instrument/Apps/EPICS/support/webget/master'
./webgetApp/src/O.windows-x64/runner --gtest_output=xml:./test-reports/TEST-Webget.xml
make: *** [Makefile:25: test] Error -1073741701
make: Leaving directory 'c:/Instrument/Apps/EPICS/support/webget/master'
```

I have checked that `support\googletest` is up to date and rebuilt. Any ideas?

**Comment by FreddieAkeroyd** [comment]
Ah, it was missing DLL path - I happened to be running on a static build. Try now.

**Review by Tom-Willemsen — APPROVED** [review]

**Pull request merged**
